java_test(
    name = "BarFactoryTest",
    srcs = ["BarFactoryTest.java"],
    deps = [
        "//src/main/java/com/verlumen/tradestar/core/candles:granularity_spec",
        "//src/main/java/com/verlumen/tradestar/core/tradehistory:bar_factory",
        "@maven//:com_google_testparameterinjector_test_parameter_injector",
        "@maven//:com_google_truth_extensions_truth_java8_extension",
        "@maven//:com_google_truth_truth",
        "@maven//:org_ta4j_ta4j_core",
        "@tradestar_protos//:candles_java_proto",
        "@tradestar_protos//:timestamp_java_proto",
    ],
)
