java_test(
    name = "AdapterBasedTradeStrategyGeneratorTest",
    srcs = ["AdapterBasedTradeStrategyGeneratorTest.java"],
    deps = [
        "//:autovalue",
        "//src/main/java/com/verlumen/tradestar/core/strategies/adapters:trade_strategy_adapter",
        "//src/main/java/com/verlumen/tradestar/core/strategies/generators:adapter_based_trade_strategy_generator",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_extensions_guice_testlib",
        "@maven//:com_google_inject_guice",
        "@maven//:com_google_testparameterinjector_test_parameter_injector",
        "@maven//:com_google_truth_truth",
        "@maven//:org_ta4j_ta4j_core",
        "@tradestar_protos//:strategies_java_proto",
    ],
)
