java_test(
    name = "StrategyFactoryImplTest",
    srcs = ["StrategyFactoryImplTest.java"],
    deps = [
        "//src/main/java/com/verlumen/tradestar/core/ta/rules:rule_factory",
        "//src/main/java/com/verlumen/tradestar/core/ta/strategies:strategy_factory_impl",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_extensions_guice_testlib",
        "@maven//:com_google_inject_guice",
        "@maven//:com_google_testparameterinjector_test_parameter_injector",
        "@maven//:com_google_truth_extensions_truth_java8_extension",
        "@maven//:com_google_truth_truth",
        "@maven//:org_ta4j_ta4j_core",
        "@tradestar_protos//:strategies_java_proto",
    ],
)
