java_test(
    name = "CandleFactoryTest",
    srcs = ["CandleFactoryTest.java"],
    deps = [
        "//src/main/java/com/verlumen/tradestar/core/candles:candle_factory",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_extensions_guice_testlib",
        "@maven//:com_google_inject_guice",
        "@maven//:com_google_testparameterinjector_test_parameter_injector",
        "@maven//:com_google_truth_extensions_truth_java8_extension",
        "@maven//:com_google_truth_truth",
        "@tradestar_protos//:candles_java_proto",
        "@tradestar_protos//:instruments_java_proto",
        "@tradestar_protos//:trading_java_proto",
    ],
)

java_test(
    name = "GranularitySpecTest",
    srcs = ["GranularitySpecTest.java"],
    deps = [
        "//src/main/java/com/verlumen/tradestar/core/candles:granularity_spec",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_extensions_guice_testlib",
        "@maven//:com_google_testparameterinjector_test_parameter_injector",
        "@maven//:com_google_truth_extensions_truth_java8_extension",
        "@maven//:com_google_truth_truth",
        "@tradestar_protos//:candles_java_proto",
    ],
)
