java_test(
    name = "AdxRuleAdapterTest",
    srcs = ["AdxRuleAdapterTest.java"],
    deps = [
        "//src/main/java/com/verlumen/tradestar/core/ta/indicators:indicator_factory",
        "//src/main/java/com/verlumen/tradestar/core/ta/rules/adapters:adx_rule_adapter",
        "//src/main/java/com/verlumen/tradestar/core/ta/signalstrength:signal_strength_module",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_guice",
        "@maven//:com_google_testparameterinjector_test_parameter_injector",
        "@maven//:com_google_truth_extensions_truth_java8_extension",
        "@maven//:com_google_truth_truth",
        "@maven//:org_ta4j_ta4j_core",
        "@tradestar_protos//:strategies_java_proto",
    ],
)
