java_test(
    name = "AdxTradeStrategyAdapterTest",
    srcs = ["AdxTradeStrategyAdapterTest.java"],
    deps = [
        "//src/main/java/com/verlumen/tradestar/core/strategies/adapters:adx_trade_strategy_adapter",
        "@maven//:com_google_inject_extensions_guice_testlib",
        "@maven//:com_google_inject_guice",
        "@maven//:com_google_testparameterinjector_test_parameter_injector",
        "@tradestar_protos//:strategies_java_proto",
        "@maven//:com_google_truth_truth",
    ],
)
